/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Enter a weather station name": {                "en": "Enter a weather station name",                    "de": "Name einer Wetterstation eingeben",               "ru": "Введите название метеостанции",                   "pt": "Insira o nome de uma estação meteorológica",      "nl": "Voer de naam van een weerstation in",             "fr": "Entrer un nom de station météo",                  "it": "Immettere il nome di una stazione meteorologica", "es": "Ingrese un nombre de estación meteorológica",     "pl": "Wprowadź nazwę stacji pogodowej",                 "zh-cn": "输入气象站名称"},
    "Enter a zip code or town": {                    "en": "Enter a zip code or town",                        "de": "Postleitzahl oder Ort eingeben",                  "ru": "Введите почтовый индекс или город",               "pt": "Insira um código postal ou cidade",               "nl": "Voer een postcode of plaats in",                  "fr": "Entrer un code postal ou une ville",              "it": "Inserisci un codice postale o una città",         "es": "Ingrese un código postal o ciudad",               "pl": "Wpisz kod pocztowy lub miasto",                   "zh-cn": "输入邮政编码或城镇"},
    "Language": {                                    "en": "Language",                                        "de": "Sprache",                                         "ru": "Язык",                                            "pt": "Língua",                                          "nl": "Taal",                                            "fr": "Langue",                                          "it": "Linguaggio",                                      "es": "Idioma",                                          "pl": "Język",                                           "zh-cn": "语言"},
    "Locations": {                                   "en": "Locations",                                       "de": "Ortschaften",                                     "ru": "Локации",                                         "pt": "Localizações",                                    "nl": "Locaties",                                        "fr": "Lieux",                                           "it": "Località",                                        "es": "Ubicaciones",                                     "pl": "Lokalizacje",                                     "zh-cn": "地点"},
    "Weather Stations": {                            "en": "Weather Stations",                                "de": "Wetterstationen",                                 "ru": "Метеостанции",                                    "pt": "Estações meteorológicas",                         "nl": "Weerstations",                                    "fr": "Stations météo",                                  "it": "Stazioni meteorologiche",                         "es": "Estaciones meteorológicas",                       "pl": "Stacje pogodowe",                                 "zh-cn": "气象站"},
    "add stations": {                                "en": "add stations",                                    "de": "Stationen hinzufügen",                            "ru": "добавить станции",                                "pt": "adicionar estações",                              "nl": "stations toevoegen",                              "fr": "ajouter des stations",                            "it": "aggiungi stazioni",                               "es": "agregar estaciones",                              "pl": "dodać stacje",                                    "zh-cn": "加站"},
    "add towns": {                                   "en": "add towns",                                       "de": "Orte hinzufügen",                                 "ru": "добавить города",                                 "pt": "adicionar cidades",                               "nl": "steden toevoegen",                                "fr": "ajouter des lieux",                               "it": "aggiungi località",                               "es": "agregar ciudades",                                "pl": "dodaj miasta",                                    "zh-cn": "添加城镇"},
    "meteoswiss adapter settings": {                 "en": "Adapter settings for meteoswiss",                 "de": "Adaptereinstellungen für meteoswiss",             "ru": "Настройки адаптера для meteoswiss",               "pt": "Configurações do adaptador para meteoswiss",      "nl": "Adapterinstellingen voor meteoswiss",             "fr": "Paramètres d'adaptateur pour meteoswiss",         "it": "Impostazioni dell'adattatore per meteoswiss",     "es": "Ajustes del adaptador para meteoswiss",           "pl": "Ustawienia adaptera dla meteoswiss",              "zh-cn": "meteoswiss的适配器设置"},
};